[solr]
host="http://localhost"
port=8983
username=""
password=""
collection="gettingstarted"

[opensearch]
domain="{{DOMAIN_NAME}}"
bucket="{{BUCKET_NAME}}"
host="{{OPENSEARCH_HOST}}"
port=443
region="{{AWS_REGION}}"
use_aws_auth_sigv4=true
username=""
password=""
index="{{INDEX_NAME}}"
use_ssl=true
assert_hostname=false
verify_certs=true


[migration]
create_package=true
expand_files_array=false
create_index=false
migrate_schema=true
skip_text_analysis_failure=false

[data_migration]
migrate_data=true
s3_export_bucket="{{BUCKET_NAME}}"
s3_export_prefix="migration_data/"
region="{{AWS_REGION}}"
batch_size=1000
rows_per_page=500
max_rows=100000
